### ISSUE TITLE
Lines in PDF creation of Weblogo for Protein Alignment

### ISSUE THREAD

**Issue by RoKant** [omarwagih/RWebLogo#2]
Hi Omar Wagih,

I have a problem with the RWebLogo package.
I have nice Alignment of Short Peptide stretches.
Everything works fine, but when I create the plots, some lines appear.
Any idea what I'm doing wrong?

Line I use to call the weblogo function:
weblogo(open=FALSE,seqs=test6$Sequence,size="large",scale.width = FALSE,aspect.ratio = 2.2,file.out= paste("./Plots/Weblogos/",chotnumsnames[j],"_Weblogo_",subgroup,".pdf",sep=""),sequence.type="protein",composition="none",units="probability",annotate=Chothianums,errorbars=FALSE,color.scheme="chemistry")

Pdf I get:
[L95Chothia_Weblogo_Kiii.pdf](https://github.com/omarwagih/RWebLogo/files/1139185/L95Chothia_Weblogo_Kiii.pdf)

As you see there are some annoying lines in the final product. Did I miss a variable? Or use some wrong setting?

Cheers,
Rob

**Comment by omarwagih** [comment]
Hi @RoKant, RWeblogo is no longer maintained, please use ggseqlogo instead: https://github.com/omarwagih/ggseqlogo
