### ISSUE TITLE
Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by kalimero0411** [omarwagih/RWebLogo#5]
I get an error even with the example input:

aln <- c('CCAACCCAA', 'CCAACCCTA', 'AAAGCCTGA', 'TGAACCGGA')
weblogo(seqs=aln, return.cmd = TRUE)

> **Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()**
> Sequence logo saved to /home/kalimero/Desktop/SINEs/RWebLogo.pdf
> [1] "/home/kalimero/R/x86_64-pc-linux-gnu-library/3.6/RWebLogo/extdata/weblogo-3.3/weblogo < /tmp/RtmpkgFUnN/tmp.logo > /home/kalimero/Desktop/SINEs/RWebLogo.pdf --format 'pdf' --size 'large' --fineprint ''"

sessionInfo()

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.3 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
> 
> locale:
>  [1] LC_CTYPE=en_IL.UTF-8       LC_NUMERIC=C               LC_TIME=en_IL.UTF-8        LC_COLLATE=en_IL.UTF-8     LC_MONETARY=en_IL.UTF-8   
>  [6] LC_MESSAGES=en_IL.UTF-8    LC_PAPER=en_IL.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_IL.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] tcltk     stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] RWebLogo_1.0.3
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.1   tools_3.6.1      findpython_1.0.5

python --version

> Python 2.7.15+

python3 --version

> Python 3.6.8

How can I solve this?

Thank you.

**Comment by GildasLepennetier** [comment]
Any new on this issue?

**Comment by omarwagih** [comment]
RWebLogo is outdated and no longer maintained
Please use ggseqlogo https://github.com/omarwagih/ggseqlogo

**Comment by GildasLepennetier** [comment]
Ok, thanks!!
